// src/components/camera/ReportScreen.tsx
import React, { useState, useEffect, useRef } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  TouchableOpacity, 
  ScrollView, 
  ActivityIndicator, 
  Alert, 
  Share,
  Image,
  Animated,
  Dimensions
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useTheme } from '@/src/context/ThemeContext';
import { getThemeStyles, horizontalScale, verticalScale, moderateScale } from '@/src/theme';
import { MaterialIcons, Feather } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import { Receipt } from '@/src/types/ReceiptInterfaces';
import { DocumentStorage } from '@/src/services/DocumentStorage';
import * as Haptics from 'expo-haptics';

const { width } = Dimensions.get('window');

export default function ReportScreen() {
  const params = useLocalSearchParams();
  const router = useRouter();
  const { t } = useTranslation();
  const { theme } = useTheme();
  const themeStyles = getThemeStyles(theme);
  
  // Parse the receipt data
  const [receipt, setReceipt] = useState<Receipt | null>(
    params.receipt ? JSON.parse(params.receipt as string) : null
  );
  
  const [isStatusUpdating, setIsStatusUpdating] = useState(false);
  const [shareLoading, setShareLoading] = useState(false);
  const [showFullText, setShowFullText] = useState(false);
  
  // Animation refs
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const slideAnim = useRef(new Animated.Value(50)).current;
  
  // Animate components in on mount
  useEffect(() => {
    Animated.parallel([
      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: 600,
        useNativeDriver: true
      }),
      Animated.timing(slideAnim, {
        toValue: 0,
        duration: 600,
        useNativeDriver: true
      })
    ]).start();
  }, []);
  
  // Format date for display
  const formatDate = (dateString?: string) => {
    if (!dateString) return '';
    
    try {
      // Try to parse as ISO date first
      const date = new Date(dateString);
      
      // Check if valid date
      if (isNaN(date.getTime())) {
        // If not valid ISO date, just return as is
        return dateString;
      }
      
      return date.toLocaleDateString(undefined, { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric'
      });
    } catch (e) {
      return dateString;
    }
  };
  
  // Format time for display
  const formatTime = (dateString?: string) => {
    if (!dateString) return '';
    
    try {
      const date = new Date(dateString);
      
      // Check if valid date
      if (isNaN(date.getTime())) {
        return '';
      }
      
      return date.toLocaleTimeString(undefined, {
        hour: '2-digit',
        minute: '2-digit'
      });
    } catch (e) {
      return '';
    }
  };
  
  // Handle approval of the document
  const handleApproveDocument = async () => {
    if (!receipt?.id) return;
    
    setIsStatusUpdating(true);
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    
    try {
      const updated = await DocumentStorage.updateReceiptStatus(receipt.id, 'Approved');
      if (updated) {
        setReceipt(updated);
        
        // Success feedback
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
        
        Alert.alert(
          t('success', 'Success'),
          t('receiptApproved', 'Receipt has been approved successfully')
        );
      }
    } catch (error) {
      console.error('Error approving document:', error);
      
      // Error feedback
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
      
      Alert.alert(
        t('error', 'Error'),
        t('errorUpdatingStatus', 'Failed to update receipt status')
      );
    } finally {
      setIsStatusUpdating(false);
    }
  };
  
  // Toggle full text display
  const toggleFullText = () => {
    setShowFullText(!showFullText);
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
  };
  
  // Share document content
  const handleShareDocument = async () => {
    if (!receipt) return;
    
    setShareLoading(true);
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    
    try {
      // Create a simple text representation
      const textContent = `
📝 Receipt Report
-----------------------
🏢 Vendor: ${receipt.vendorName || 'Unknown'}
💰 Amount: ${receipt.amount}
📅 Date: ${formatDate(receipt.date)}
🚚 Vehicle: ${receipt.vehicle}
🔤 Type: ${receipt.type}
📍 Location: ${receipt.location || 'Not specified'}
📋 Status: ${receipt.status}
-----------------------
📝 Raw Text:
${receipt.extractedText}

Generated by Trucking Logistics Pro
      `;
      
      await Share.share({
        message: textContent,
        title: 'Receipt Report',
      });
      
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (error) {
      console.error('Error sharing document:', error);
      
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
      
      Alert.alert(
        t('error', 'Error'),
        t('errorSharing', 'Failed to share the receipt')
      );
    } finally {
      setShareLoading(false);
    }
  };
  
  // Go back to the reports screen
  const handleFinish = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    router.push('/reports');
  };
  
  // Get appropriate icon for receipt type
  const getReceiptTypeIcon = (type?: string) => {
    switch (type?.toLowerCase()) {
      case 'fuel': return 'local-gas-station';
      case 'maintenance': return 'build';
      default: return 'receipt';
    }
  };
  
  if (!receipt) {
    return (
      <View style={[
        styles.loadingContainer,
        { backgroundColor: themeStyles.colors.black_grey }
      ]}>
        <ActivityIndicator size="large" color={themeStyles.colors.greenThemeColor} />
        <Text style={[
          styles.loadingText,
          { color: themeStyles.colors.white }
        ]}>{t('loadingReceipt', 'Loading receipt...')}</Text>
      </View>
    );
  }

  return (
    <View style={[
      styles.container,
      { backgroundColor: themeStyles.colors.black_grey }
    ]}>
      {/* Header */}
      <View style={[
        styles.header,
        { 
          borderBottomColor: themeStyles.colors.darkGrey
        }
      ]}>
        <TouchableOpacity 
          style={[
            styles.backButton,
            { backgroundColor: themeStyles.colors.darkGrey }
          ]} 
          onPress={() => {
            Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
            router.back();
          }}
        >
          <MaterialIcons name="arrow-back" size={24} color={themeStyles.colors.white} />
        </TouchableOpacity>
        <Text style={[
          styles.headerTitle,
          { color: themeStyles.colors.white }
        ]}>{t('receiptReport', 'Receipt Report')}</Text>
        <TouchableOpacity 
          style={[
            styles.shareButton, 
            { backgroundColor: themeStyles.colors.darkGrey },
            shareLoading && { opacity: 0.6 }
          ]} 
          onPress={handleShareDocument}
          disabled={shareLoading}
        >
          {shareLoading ? (
            <ActivityIndicator size="small" color={themeStyles.colors.white} />
          ) : (
            <Feather name="share" size={20} color={themeStyles.colors.white} />
          )}
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        <View style={styles.contentContainer}>
          {/* Status Banner */}
          <Animated.View 
            style={[
              styles.statusBanner,
              receipt.status === 'Approved' ? 
                { 
                  backgroundColor: themeStyles.colors.status.success + '22',
                  borderColor: themeStyles.colors.status.success 
                } : 
                { 
                  backgroundColor: themeStyles.colors.status.warning + '22',
                  borderColor: themeStyles.colors.status.warning 
                },
              {
                opacity: fadeAnim,
                transform: [{ translateY: slideAnim }]
              }
            ]}
          >
            <MaterialIcons 
              name={receipt.status === 'Approved' ? "check-circle" : "pending"} 
              size={24} 
              color={receipt.status === 'Approved' ? 
                themeStyles.colors.status.success : 
                themeStyles.colors.status.warning
              } 
            />
            <Text style={[
              styles.statusText,
              { color: themeStyles.colors.white }
            ]}>
              {receipt.status === 'Approved' 
                ? t('approved', 'Approved') 
                : t('pendingApproval', 'Pending Approval')}
            </Text>
          </Animated.View>
          
          {/* Receipt Header */}
          <Animated.View 
            style={[
              styles.receiptCard,
              {
                backgroundColor: themeStyles.colors.darkGrey,
                ...themeStyles.shadow.md,
                opacity: fadeAnim,
                transform: [{ translateY: slideAnim }]
              }
            ]}
          >
            <View style={styles.receiptHeader}>
              <View style={styles.receiptType}>
                <MaterialIcons 
                  name={getReceiptTypeIcon(receipt.type)} 
                  size={24} 
                  color={themeStyles.colors.greenThemeColor} 
                />
                <Text style={[
                  styles.receiptTypeText,
                  { color: themeStyles.colors.white }
                ]}>{receipt.type || 'Other'}</Text>
              </View>
              <View style={styles.receiptDate}>
                <Text style={[
                  styles.dateText,
                  { color: themeStyles.colors.white }
                ]}>{formatDate(receipt.date)}</Text>
                <Text style={[
                  styles.timeText,
                  { color: themeStyles.colors.grey }
                ]}>{formatTime(receipt.timestamp)}</Text>
              </View>
            </View>
            
            <View style={[
              styles.divider,
              { backgroundColor: themeStyles.colors.black_grey }
            ]} />
            
            {/* Main Receipt Content */}
            <View style={styles.receiptContent}>
              <Text style={[
                styles.amountText,
                { color: themeStyles.colors.white }
              ]}>{receipt.amount}</Text>
              <Text style={[
                styles.vendorText,
                { color: themeStyles.colors.white }
              ]}>{receipt.vendorName || t('unknownVendor', 'Unknown Vendor')}</Text>
              
              <View style={styles.detailsGrid}>
                <View style={styles.detailItem}>
                  <Text style={[
                    styles.detailLabel,
                    { color: themeStyles.colors.grey }
                  ]}>{t('vehicle', 'Vehicle')}</Text>
                  <Text style={[
                    styles.detailValue,
                    { color: themeStyles.colors.white }
                  ]}>{receipt.vehicle}</Text>
                </View>
                
                {receipt.location && (
                  <View style={styles.detailItem}>
                    <Text style={[
                      styles.detailLabel,
                      { color: themeStyles.colors.grey }
                    ]}>{t('location', 'Location')}</Text>
                    <Text style={[
                      styles.detailValue,
                      { color: themeStyles.colors.white }
                    ]} numberOfLines={2}>{receipt.location}</Text>
                  </View>
                )}
                
                <View style={styles.detailItem}>
                  <Text style={[
                    styles.detailLabel,
                    { color: themeStyles.colors.grey }
                  ]}>{t('receiptId', 'Receipt ID')}</Text>
                  <Text style={[
                    styles.detailValue,
                    { color: themeStyles.colors.white }
                  ]}>{receipt.id.substring(0, 8)}</Text>
                </View>
              </View>
            </View>
          </Animated.View>
          
          {/* Raw Text Section */}
          <Animated.View 
            style={[
              styles.rawTextCard,
              {
                backgroundColor: themeStyles.colors.darkGrey,
                ...themeStyles.shadow.sm,
                opacity: fadeAnim,
                transform: [{ translateY: slideAnim }]
              }
            ]}
          >
            <TouchableOpacity 
              style={[
                styles.rawTextHeader,
                { borderBottomColor: themeStyles.colors.black_grey }
              ]}
              onPress={toggleFullText}
            >
              <View style={styles.rawTextTitle}>
                <Feather name="file-text" size={20} color={themeStyles.colors.greenThemeColor} />
                <Text style={[
                  styles.rawTextTitleText,
                  { color: themeStyles.colors.white }
                ]}>{t('extractedText', 'Extracted Text')}</Text>
              </View>
              <Feather 
                name={showFullText ? "chevron-up" : "chevron-down"} 
                size={20} 
                color={themeStyles.colors.grey} 
              />
            </TouchableOpacity>
            
            <View style={[
              styles.rawTextContent,
              !showFullText && styles.rawTextContentCollapsed
            ]}>
              <Text style={[
                styles.rawText,
                { color: themeStyles.colors.grey }
              ]}>
                {receipt.extractedText || t('noTextExtracted', 'No text was extracted from this receipt.')}
              </Text>
            </View>
            
            {!showFullText && receipt.extractedText && receipt.extractedText.length > 100 && (
              <TouchableOpacity 
                style={[
                  styles.showMoreButton,
                  { backgroundColor: themeStyles.colors.black_grey }
                ]}
                onPress={toggleFullText}
              >
                <Text style={[
                  styles.showMoreText,
                  { color: themeStyles.colors.greenThemeColor }
                ]}>{t('showMore', 'Show More')}</Text>
              </TouchableOpacity>
            )}
          </Animated.View>
          
          {/* Action Card */}
          <Animated.View 
            style={[
              styles.actionCard,
              {
                backgroundColor: themeStyles.colors.darkGrey,
                ...themeStyles.shadow.sm,
                opacity: fadeAnim,
                transform: [{ translateY: slideAnim }]
              }
            ]}
          >
            <Text style={[
              styles.actionTitle,
              { color: themeStyles.colors.white }
            ]}>{t('actions', 'Actions')}</Text>
            
            <View style={styles.actionButtons}>
              {receipt.status === 'Pending' ? (
                <TouchableOpacity 
                  style={[
                    styles.approveButton, 
                    { 
                      backgroundColor: themeStyles.colors.status.success,
                      ...themeStyles.shadow.sm
                    },
                    isStatusUpdating && { opacity: 0.6 }
                  ]} 
                  onPress={handleApproveDocument}
                  disabled={isStatusUpdating}
                >
                  {isStatusUpdating ? (
                    <ActivityIndicator size="small" color={themeStyles.colors.white} />
                  ) : (
                    <>
                      <MaterialIcons name="check-circle" size={20} color={themeStyles.colors.white} />
                      <Text style={[
                        styles.buttonText,
                        { color: themeStyles.colors.white }
                      ]}>{t('approve', 'Approve')}</Text>
                    </>
                  )}
                </TouchableOpacity>
              ) : (
                <View style={[
                  styles.approvedMessage,
                  { backgroundColor: themeStyles.colors.black_grey }
                ]}>
                  <MaterialIcons name="check-circle" size={20} color={themeStyles.colors.status.success} />
                  <Text style={[
                    styles.approvedText,
                    { color: themeStyles.colors.status.success }
                  ]}>{t('receiptApproved', 'Receipt Approved')}</Text>
                </View>
              )}
              
              <TouchableOpacity 
                style={[
                  styles.shareActionButton,
                  { 
                    backgroundColor: themeStyles.colors.black_grey,
                    ...themeStyles.shadow.sm
                  }
                ]}
                onPress={handleShareDocument}
              >
                <Feather name="share-2" size={20} color={themeStyles.colors.white} />
                <Text style={[
                  styles.buttonText,
                  { color: themeStyles.colors.white }
                ]}>{t('share', 'Share')}</Text>
              </TouchableOpacity>
            </View>
          </Animated.View>
        </View>
      </ScrollView>

      {/* Footer */}
      <View style={[
        styles.footer,
        { 
          backgroundColor: themeStyles.colors.black_grey,
          borderTopColor: themeStyles.colors.darkGrey,
          ...themeStyles.shadow.lg
        }
      ]}>
        <TouchableOpacity 
          style={[
            styles.doneButton,
            { 
              backgroundColor: themeStyles.colors.greenThemeColor,
              ...themeStyles.shadow.md
            }
          ]} 
          onPress={handleFinish}
        >
          <Text style={[
            styles.buttonText,
            { color: themeStyles.colors.white }
          ]}>{t('done', 'Done')}</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: verticalScale(16),
    fontSize: moderateScale(14),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: horizontalScale(16),
    paddingTop: verticalScale(60),
    paddingBottom: verticalScale(16),
    borderBottomWidth: 1,
  },
  backButton: {
    padding: moderateScale(8),
    borderRadius: moderateScale(20),
  },
  shareButton: {
    padding: moderateScale(8),
    borderRadius: moderateScale(20),
  },
  headerTitle: {
    fontSize: moderateScale(18),
    fontWeight: 'bold',
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    padding: horizontalScale(16),
    paddingBottom: verticalScale(100),
  },
  statusBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
    marginBottom: verticalScale(16),
    borderWidth: 1,
  },
  statusText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    marginLeft: horizontalScale(8),
  },
  receiptCard: {
    borderRadius: moderateScale(12),
    padding: horizontalScale(16),
    marginBottom: verticalScale(16),
  },
  receiptHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: verticalScale(8),
  },
  receiptType: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  receiptTypeText: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    marginLeft: horizontalScale(8),
  },
  receiptDate: {
    alignItems: 'flex-end',
  },
  dateText: {
    fontSize: moderateScale(14),
  },
  timeText: {
    fontSize: moderateScale(12),
    marginTop: 2,
  },
  divider: {
    height: 1,
    marginVertical: verticalScale(8),
  },
  receiptContent: {
    paddingVertical: verticalScale(8),
  },
  amountText: {
    fontSize: moderateScale(24),
    fontWeight: 'bold',
    marginBottom: verticalScale(4),
  },
  vendorText: {
    fontSize: moderateScale(16),
    marginBottom: verticalScale(16),
  },
  detailsGrid: {
    marginTop: verticalScale(8),
  },
  detailItem: {
    marginBottom: verticalScale(8),
  },
  detailLabel: {
    fontSize: moderateScale(12),
    marginBottom: 2,
  },
  detailValue: {
    fontSize: moderateScale(14),
    fontWeight: '500',
  },
  rawTextCard: {
    borderRadius: moderateScale(12),
    marginBottom: verticalScale(16),
    overflow: 'hidden',
  },
  rawTextHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: horizontalScale(16),
    borderBottomWidth: 1,
  },
  rawTextTitle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rawTextTitleText: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    marginLeft: horizontalScale(8),
  },
  rawTextContent: {
    padding: horizontalScale(16),
  },
  rawTextContentCollapsed: {
    maxHeight: verticalScale(100),
    overflow: 'hidden',
  },
  rawText: {
    fontSize: moderateScale(12),
    lineHeight: moderateScale(16),
  },
  showMoreButton: {
    alignItems: 'center',
    padding: verticalScale(8),
  },
  showMoreText: {
    fontSize: moderateScale(12),
    fontWeight: '600',
  },
  actionCard: {
    borderRadius: moderateScale(12),
    padding: horizontalScale(16),
  },
  actionTitle: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    marginBottom: verticalScale(16),
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: horizontalScale(8),
  },
  approveButton: {
    flex: 1,
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  shareActionButton: {
    flex: 1,
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  buttonText: {
    fontSize: moderateScale(16),
    fontWeight: 'bold',
    marginLeft: horizontalScale(8),
  },
  approvedMessage: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
  },
  approvedText: {
    marginLeft: horizontalScale(8),
    fontSize: moderateScale(14),
    fontWeight: '500',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: horizontalScale(16),
    borderTopWidth: 1,
  },
  doneButton: {
    padding: moderateScale(16),
    borderRadius: moderateScale(12),
    alignItems: 'center',
    justifyContent: 'center',
  }
});